### ISSUE TITLE
Proposal to use another font

### ISSUE THREAD

**Issue by MatteoGauthier** [liyasthomas/colorbook#1]
Hello, I noticed that you used the Google Object Sans font, it seems to me that it is not free.
As an alternative, you can use :
* https://github.com/sharanda/manrope
* https://www.myfonts.com/fonts/radomir-tinkov/gilroy/
* Roboto

**Comment by liyasthomas** [comment]
@MattixNow Thanks for the proposal. Issue has been noticed, and will be fixed in next commit.
