### ISSUE TITLE
Filter non-a11y color combos?

### ISSUE THREAD

**Issue by r-i-c-h** [liyasthomas/colorbook#2]
Sorry I don't have time to take this on myself, but something that is noticeable is that Colorbook random Foreground/Background comes up with some pretty inaccessible color combinations (aka, foregrounds that are difficult/impossible to read against their background). 
Perhaps consider a filter to the random color generator that will nix or warn about poor color contrasts?

**Comment by liyasthomas** [comment]
Issue has been identified. Will look into it.

**Comment by asnimansari** [comment]
I believe using WCAG Contrast checking logic and filtering out poorly graded colour combinations will fix this issue
